USE [master]
GO

if db_id('GISA') is null
	CREATE DATABASE [GISA]  
GO

ALTER DATABASE [GISA] SET COMPATIBILITY_LEVEL = 80
GO

ALTER DATABASE [GISA] SET ARITHABORT ON
GO

ALTER DATABASE [GISA] SET QUOTED_IDENTIFIER ON
GO

ALTER DATABASE [GISA] COLLATE Latin1_General_CS_AS
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GISA].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [GISA] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [GISA] SET ANSI_NULLS ON 
GO

ALTER DATABASE [GISA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GISA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GISA] SET ARITHABORT OFF 
GO

ALTER DATABASE [GISA] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GISA] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GISA] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [GISA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GISA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GISA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GISA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GISA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GISA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GISA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GISA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GISA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GISA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GISA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GISA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GISA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GISA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GISA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GISA] SET  READ_WRITE 
GO

ALTER DATABASE [GISA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GISA] SET  MULTI_USER 
GO

ALTER DATABASE [GISA] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [GISA] SET DB_CHAINING OFF 
GO

USE [GISA]
GO


