//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GISA.Webservices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.10.0.131/CMPWSDocumentos/ServicoDocumentos.asmx")]
        public string GISA_Webservices_DocInPortoWebservice_ServicoDocumentos {
            get {
                return ((string)(this["GISA_Webservices_DocInPortoWebservice_ServicoDocumentos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.10.11.25:1500/cmpwstoponimia/toponimia.asmx")]
        public string GISA_Webservices_Pre_ToponimiaWS_ToponimiaWS {
            get {
                return ((string)(this["GISA_Webservices_Pre_ToponimiaWS_ToponimiaWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://servicoscmp.cm-porto.net/cmpwstoponimia/toponimia.asmx")]
        public string GISA_Webservices_ToponimiaWS_ToponimiaWS {
            get {
                return ((string)(this["GISA_Webservices_ToponimiaWS_ToponimiaWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://docinporto.cm-porto.net/CMPWSDocumentos/ServicoDocumentos.asmx")]
        public string GISA_Webservices_ProdDocInPortoWebService_ServicoDocumentos {
            get {
                return ((string)(this["GISA_Webservices_ProdDocInPortoWebService_ServicoDocumentos"]));
            }
        }
    }
}
