//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace GISA.Webservices.Pre_ToponimiaWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ToponimiaWSSoap", Namespace="http://tempuri.org/")]
    public partial class ToponimiaWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsereToponimiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminaToponimiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizaToponimiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PesquisaToponimiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SeleccionaToponimiaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ToponimiaWS() {
            this.Url = global::GISA.Webservices.Properties.Settings.Default.GISA_Webservices_Pre_ToponimiaWS_ToponimiaWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsereToponimiaCompletedEventHandler InsereToponimiaCompleted;
        
        /// <remarks/>
        public event EliminaToponimiaCompletedEventHandler EliminaToponimiaCompleted;
        
        /// <remarks/>
        public event ActualizaToponimiaCompletedEventHandler ActualizaToponimiaCompleted;
        
        /// <remarks/>
        public event PesquisaToponimiaCompletedEventHandler PesquisaToponimiaCompleted;
        
        /// <remarks/>
        public event SeleccionaToponimiaCompletedEventHandler SeleccionaToponimiaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsereToponimia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsereToponimia(string codmorada, string morada) {
            object[] results = this.Invoke("InsereToponimia", new object[] {
                        codmorada,
                        morada});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsereToponimiaAsync(string codmorada, string morada) {
            this.InsereToponimiaAsync(codmorada, morada, null);
        }
        
        /// <remarks/>
        public void InsereToponimiaAsync(string codmorada, string morada, object userState) {
            if ((this.InsereToponimiaOperationCompleted == null)) {
                this.InsereToponimiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsereToponimiaOperationCompleted);
            }
            this.InvokeAsync("InsereToponimia", new object[] {
                        codmorada,
                        morada}, this.InsereToponimiaOperationCompleted, userState);
        }
        
        private void OnInsereToponimiaOperationCompleted(object arg) {
            if ((this.InsereToponimiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsereToponimiaCompleted(this, new InsereToponimiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminaToponimia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EliminaToponimia(string codmorada) {
            object[] results = this.Invoke("EliminaToponimia", new object[] {
                        codmorada});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EliminaToponimiaAsync(string codmorada) {
            this.EliminaToponimiaAsync(codmorada, null);
        }
        
        /// <remarks/>
        public void EliminaToponimiaAsync(string codmorada, object userState) {
            if ((this.EliminaToponimiaOperationCompleted == null)) {
                this.EliminaToponimiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminaToponimiaOperationCompleted);
            }
            this.InvokeAsync("EliminaToponimia", new object[] {
                        codmorada}, this.EliminaToponimiaOperationCompleted, userState);
        }
        
        private void OnEliminaToponimiaOperationCompleted(object arg) {
            if ((this.EliminaToponimiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminaToponimiaCompleted(this, new EliminaToponimiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizaToponimia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ActualizaToponimia(string codmorada, string morada) {
            object[] results = this.Invoke("ActualizaToponimia", new object[] {
                        codmorada,
                        morada});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaToponimiaAsync(string codmorada, string morada) {
            this.ActualizaToponimiaAsync(codmorada, morada, null);
        }
        
        /// <remarks/>
        public void ActualizaToponimiaAsync(string codmorada, string morada, object userState) {
            if ((this.ActualizaToponimiaOperationCompleted == null)) {
                this.ActualizaToponimiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaToponimiaOperationCompleted);
            }
            this.InvokeAsync("ActualizaToponimia", new object[] {
                        codmorada,
                        morada}, this.ActualizaToponimiaOperationCompleted, userState);
        }
        
        private void OnActualizaToponimiaOperationCompleted(object arg) {
            if ((this.ActualizaToponimiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaToponimiaCompleted(this, new ActualizaToponimiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PesquisaToponimia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet PesquisaToponimia(string morada) {
            object[] results = this.Invoke("PesquisaToponimia", new object[] {
                        morada});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PesquisaToponimiaAsync(string morada) {
            this.PesquisaToponimiaAsync(morada, null);
        }
        
        /// <remarks/>
        public void PesquisaToponimiaAsync(string morada, object userState) {
            if ((this.PesquisaToponimiaOperationCompleted == null)) {
                this.PesquisaToponimiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPesquisaToponimiaOperationCompleted);
            }
            this.InvokeAsync("PesquisaToponimia", new object[] {
                        morada}, this.PesquisaToponimiaOperationCompleted, userState);
        }
        
        private void OnPesquisaToponimiaOperationCompleted(object arg) {
            if ((this.PesquisaToponimiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PesquisaToponimiaCompleted(this, new PesquisaToponimiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SeleccionaToponimia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SeleccionaToponimia(string codmorada) {
            object[] results = this.Invoke("SeleccionaToponimia", new object[] {
                        codmorada});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SeleccionaToponimiaAsync(string codmorada) {
            this.SeleccionaToponimiaAsync(codmorada, null);
        }
        
        /// <remarks/>
        public void SeleccionaToponimiaAsync(string codmorada, object userState) {
            if ((this.SeleccionaToponimiaOperationCompleted == null)) {
                this.SeleccionaToponimiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeleccionaToponimiaOperationCompleted);
            }
            this.InvokeAsync("SeleccionaToponimia", new object[] {
                        codmorada}, this.SeleccionaToponimiaOperationCompleted, userState);
        }
        
        private void OnSeleccionaToponimiaOperationCompleted(object arg) {
            if ((this.SeleccionaToponimiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SeleccionaToponimiaCompleted(this, new SeleccionaToponimiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsereToponimiaCompletedEventHandler(object sender, InsereToponimiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsereToponimiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsereToponimiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EliminaToponimiaCompletedEventHandler(object sender, EliminaToponimiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminaToponimiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminaToponimiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ActualizaToponimiaCompletedEventHandler(object sender, ActualizaToponimiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaToponimiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaToponimiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PesquisaToponimiaCompletedEventHandler(object sender, PesquisaToponimiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PesquisaToponimiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PesquisaToponimiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SeleccionaToponimiaCompletedEventHandler(object sender, SeleccionaToponimiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SeleccionaToponimiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SeleccionaToponimiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591